//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace Flow.Launcher.Plugin.ProcessKiller2.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "Flow.Launcher.Plugin.ProcessKiller2.Properties.Resources",
                        typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string PluginTitle => ResourceManager.GetString("PluginTitle", resourceCulture);
        internal static string PluginDescription => ResourceManager.GetString("PluginDescription", resourceCulture);
        internal static string PortNoProcess => ResourceManager.GetString("PortNoProcess", resourceCulture);
        internal static string PortCheckOrSearchByName => ResourceManager.GetString("PortCheckOrSearchByName", resourceCulture);
        internal static string KillProcess => ResourceManager.GetString("KillProcess", resourceCulture);
        internal static string CriticalNoKill => ResourceManager.GetString("CriticalNoKill", resourceCulture);
        internal static string CriticalProcess => ResourceManager.GetString("CriticalProcess", resourceCulture);
        internal static string CriticalNoKillMessage => ResourceManager.GetString("CriticalNoKillMessage", resourceCulture);
        internal static string KillAllInstances => ResourceManager.GetString("KillAllInstances", resourceCulture);
        internal static string KillAllInstancesSubtitle => ResourceManager.GetString("KillAllInstancesSubtitle", resourceCulture);
        internal static string ListeningPortFormat => ResourceManager.GetString("ListeningPortFormat", resourceCulture);
        internal static string PortTitleSuffix => ResourceManager.GetString("PortTitleSuffix", resourceCulture);
    }
}
